version: "3"

services:

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    environment:
      RABBIT_ADDRESSES: "rabbitmq:5672"
      RABBIT_USER: "admin"
      RABBIT_PASSWORD: "admin"
    ports:
      - "9411:9411"