version: "3"

services:

  config-server:
    build:
      context: config-server
      dockerfile: Dockerfile
    container_name: config-server
    environment:
      KAFKA_BROKER_HOST: "kafka"
      KAFKA_BROKER_PORT: "9092"
    ports:
      - "8888:8888"

  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    depends_on:
      - config-server
    environment:
      KAFKA_BROKER_HOST: "kafka"
      KAFKA_BROKER_PORT: "9092"
      CONFIG_HOST: "config-server"
      CONFIG_PORT: "8888"
    ports:
      - "8761:8761"

  zuul-gateway:
    build:
      context: zuul-gateway
      dockerfile: Dockerfile
    container_name: zuul-gateway
    depends_on:
      - config-server
      - eureka-server
    environment:
      KAFKA_BROKER_HOST: "kafka"
      KAFKA_BROKER_PORT: "9092"
      CONFIG_HOST: "config-server"
      CONFIG_PORT: "8888"
      EUREKA_HOST: "eureka-server"
      EUREKA_PORT: "8761"
      ZIPKIN_HOST: "zipkin"
      ZIPKIN_PORT: "9411"
    ports:
      - "8765:8765"