spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/LybrialsGit/config-repository.git"
          cloneOnStart: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888